import useSWR from "swr";
import Head from "next/head";
import { useState } from "react";

const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Home() {
  const [siteId, setSiteId] = useState(0);
  const { data, error, isLoading } = useSWR(`https://pokeapi.co/api/v2/pokemon?offset=${siteId}`, fetcher);

  if (isLoading) {
    return <h1>Loading...</h1>;
  }

  if (error) {
    return <h1>failed to load</h1>;
  }
  console.log(data);

  return (
    <>
      <Head>
        <title>EMI - Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Pokemon List</h1>
        <ul>
          {data.results.map(({ name }) => (
            <li key={name}>{name}</li>
          ))}
        </ul>
        <button
          type="button"
          disabled={siteId === 0}
          onClick={() => {
            setSiteId((siteId) => siteId - 20);
            console.log("prev button");
          }}>
          Previous Button
        </button>
        <button
          type="button"
          onClick={() => {
            setSiteId((siteId) => siteId + 20);
            console.log("next button");
          }}>
          Next Button
        </button>
      </main>
    </>
  );
}
