import Head from "next/head";
import Image from "next/image";
import Card from "@/components/Card";

export default function Home() {
  return (
    <>
      <Head>
        <title>EMI - Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Image
          src="/images/emi-pokedex-logo.png"
          width={1000}
          height={200}
          alt="The EMI- Pokedex Logo"
          style={{ width: "80%", height: "auto", padding: "2em", margin: "auto", display: "block" }}
        />
        <Card />
      </main>
    </>
  );
}
