import useSWR from "swr";
import Head from "next/head";
import { useState } from "react";
import Image from "next/image";

const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Home() {
  const [siteId, setSiteId] = useState(0);
  const { data, error, isLoading } = useSWR(`https://pokeapi.co/api/v2/pokemon?offset=${siteId}`, fetcher);

  if (isLoading) {
    return <h1>Loading...</h1>;
  }

  if (error) {
    return <h1>failed to load</h1>;
  }
  console.log(data.results);

  return (
    <>
      <Head>
        <title>EMI - Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Pokemon List</h1>
        <div>
          {data.results.map(({ name, url }) => (
            <div key={name}>
              <h2>{name}</h2>
              <Image
                // front default
                // src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${
                //   url.split("/")[url.split("/").length - 2]
                // }.png`}
                src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/${
                  url.split("/")[url.split("/").length - 2]
                }.svg`}
                width={250}
                height={250}
                alt={name}
              />
            </div>
          ))}
        </div>
        <button
          type="button"
          disabled={siteId === 0}
          onClick={() => {
            setSiteId((siteId) => siteId - 20);
            console.log("prev button");
          }}>
          Previous Button
        </button>
        <button
          type="button"
          onClick={() => {
            setSiteId((siteId) => siteId + 20);
            console.log("next button");
          }}>
          Next Button
        </button>
      </main>
    </>
  );
}
